version: '3.9'

services:
  db:
    image: postgres:latest
    container_name: db
    ports:
      - 6500:5432
    restart: always
    env_file:
      - ./.env
    volumes:
      - postgres-db:/var/lib/postgresql/data

volumes:
  postgres-db: